# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - easyres-keukenbarscherm/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
  displayName: 'install Angular CLI'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'easyres-keukenbarscherm'
  displayName: 'npm install'

- script: |
    cd easyres-keukenbarscherm
    ng build --prod
  displayName: 'ng build'

- script: |
    cd easyres-keukenbarscherm
    ng test --watch=false --browsers=ChromeHeadless --codeCoverage=true
  displayName: 'Running Tests'

- task: ArchiveFiles@2
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    rootFolderOrFile: 'easyres-keukenbarscherm/dist/easyres-keukenbarscherm'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'